# Generated by Django 4.0 on 2022-09-05 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='Title', max_length=50)),
                ('description', models.CharField(default='description', max_length=2000)),
                ('blog_content', models.CharField(default='content', max_length=100000)),
                ('image', models.FileField(default='imgTOP', upload_to='')),
                ('middleimage', models.FileField(default='imgMIDDLE', upload_to='')),
                ('bottomimage', models.FileField(default='imgBOTTOM', upload_to='')),
                ('category', models.CharField(choices=[('General', 'General'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Socialscience', 'Socialscience'), ('Commerce', 'Commerce'), ('Computer', 'Computer'), ('Coding', 'Coding'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sports', 'Sports'), ('Health', 'Health'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='General', max_length=50)),
                ('creator', models.CharField(default='AUTHOR', max_length=20)),
                ('user', models.CharField(default='', max_length=99)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacker', models.CharField(default='DEFAULT', max_length=30)),
                ('feedbacker_userid', models.CharField(default='DEFAULT', max_length=30)),
                ('feedbacker_email', models.EmailField(default='none@gmail.com', max_length=100)),
                ('feedback', models.CharField(default='NO FEEDBACK', max_length=600)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]