# Generated by Django 4.0 on 2022-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroicBlog', '0005_remove_blog_blog_content_blog_blog_para1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_para1',
            field=models.CharField(default='Para1', max_length=100000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para2',
            field=models.CharField(default='Para2', max_length=100000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para3',
            field=models.CharField(default='Para3', max_length=100000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para4',
            field=models.CharField(default='Para4', max_length=100000),
        ),
    ]