# Generated by Django 4.0 on 2022-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroicBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bottomimage',
            field=models.FileField(default='imgBOTTOM', upload_to='heroicBlog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='imgTOP', upload_to='heroicBlog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='middleimage',
            field=models.FileField(default='imgMIDDLE', upload_to='heroicBlog/images'),
        ),
    ]