# Generated by Django 4.0 on 2022-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroicBlog', '0004_alter_blog_bottomimage_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_content',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para1',
            field=models.CharField(default='Para1', max_length=10000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para2',
            field=models.CharField(default='Para2', max_length=6000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para3',
            field=models.CharField(default='Para3', max_length=6000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para4',
            field=models.CharField(default='Para4', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='bottomimage',
            field=models.FileField(default='imgBOTTOM', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='imgTOP', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='middleimage',
            field=models.FileField(default='imgMIDDLE', upload_to=''),
        ),
    ]