# Generated by Django 4.0 on 2022-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroicBlog', '0006_alter_blog_blog_para1_alter_blog_blog_para2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_para1_heading',
            field=models.CharField(default='headingPara1', max_length=10000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para2_heading',
            field=models.CharField(default='headingPara1', max_length=10000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para3_heading',
            field=models.CharField(default='headingPara1', max_length=10000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_para4_heading',
            field=models.CharField(default='headingPara1', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para1',
            field=models.CharField(default='Para1', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para2',
            field=models.CharField(default='Para2', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para3',
            field=models.CharField(default='Para3', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para4',
            field=models.CharField(default='Para4', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Socialscience', 'Socialscience'), ('Commerce', 'Commerce'), ('Computer', 'Computer'), ('Coding', 'Coding'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sports', 'Sports'), ('Health', 'Health'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='General', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creator',
            field=models.CharField(default='AUTHOR', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='description', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
