# Generated by Django 4.0 on 2022-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroicBlog', '0008_alter_blog_blog_para1_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_para1_heading',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para2_heading',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para3_heading',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para4_heading',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
